### ISSUE TITLE
lintrunner panics on Windows

### ISSUE THREAD

**Issue by justinchuby** [suo/lintrunner#18]
Running `lintrunner` or `lintrunner init` fails with "The filename, directory name, or volume label syntax is incorrect. (os error 123)"

cargo test on Windows:

```
Error: Failed to find file while gathering files to lint: \\?\C:\Users\justinchu\AppData\Local\Temp\.tmpG29xS4/test_3.txt

Caused by:
    The filename, directory name, or volume label syntax is incorrect. (os error 123)
test git::tests::doesnt_detect_unchanged ... FAILED
Error: Failed to find file while gathering files to lint: \\?\C:\Users\justinchu\AppData\Local\Temp\.tmpziOhRn/new.txt
```

**Comment by justinchuby** [comment]
@suo Would it be possible to release a version so that it can run on windows (before all tests are enabled for it if that will take some time)?

**Comment by suo** [comment]
yeah I'll put out a release today/tomorrow.

**Comment by justinchuby** [comment]
👀🙏

**Comment by suo** [comment]
lol I lied. I'll do it now
