### ISSUE TITLE
Compact view on results

### ISSUE THREAD

**Issue by justinchuby** [suo/lintrunner#20]
Currently the source context is printed as part of the lint results. When there are many results, e.g. the change is big or when a new linter is introduced, it helps to have an option to display a compact view of the lint results, including

1. `path:line` for each lint message, so one can command click in an editor (vscode) and get straight to that line.
2. Exclude source so the messages are easier to navigate.

**Comment by suo** [comment]
does `--output oneline` do what you want?

**Comment by justinchuby** [comment]
This is exactly what I was looking for. Thanks!
