### ISSUE TITLE
Allow the pip command during init to run with `--user`

### ISSUE THREAD

**Issue by albanD** [suo/lintrunner#4]
This fails for global installs otherwise!
Shouldn't we always install with that flag?

**Comment by albanD** [comment]
From what Nikita is saying, PyTorch CI would actually use that and that would avoid the need for dry-run the init and manually adding the `--user` there.

**Comment by suo** [comment]
sorry was on PTO. The discussion here: https://stackoverflow.com/questions/33412974/how-to-uninstall-a-package-installed-with-pip-install-user/56948334#56948334 makes me nervous about this, as running with `--user` by default would break people using venvs.

Do you think we should try to detect whether we're in a virtual environment and branch on that?

**Comment by albanD** [comment]
I didn't meant to make this the default. Only to be an optin thing.
Like `lintrunner init --user` should be possible.

**Comment by suo** [comment]
Closing as it's fixed in pytorch/pytorch.

But overall lintrunner doesn't know anything about the (pytorch-specific) init commands and has no way to pass user-supplied arguments to the linters (an important design point as that is how we keep invocation uniform across all users).
