### ISSUE TITLE
Build wheels for linux aarch64

### ISSUE THREAD

**Issue by amartani** [suo/lintrunner#67]
Would it be possible to publish binary wheels for linux aarch64?

In particular, this would be useful for users running docker on arm macbooks, as these are effectively linux aarch64 systems. Currently, installing `lintrunner` on these systems requires having Cargo pre-installed, which would not be necessary if binary wheels were available.

(I can try to contribute if desired, but I have no experience with maturin and rust ecosystem in general)

```
$ pip install lintrunner
Collecting lintrunner
  Using cached lintrunner-0.12.2.tar.gz (61 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by suo** [comment]
This should be supported by maturin and thus relatively easy to add. Here is an example which builds aarch64 macos wheels: https://github.com/ezyang/tlparse/blob/main/.github/workflows/CI.yml

Feel free to make a PR for this; otherwise I'll get around it it later this week

**Comment by suo** [comment]
okay, this should be fixed and aarch wheels for macos should be available on pypi
